
obj-$(CONFIG_MSM_AMSS_VERSION_6210) += adsp_6210.o
obj-$(CONFIG_MSM_AMSS_VERSION_6220) += adsp_6220.o
obj-$(CONFIG_MSM_AMSS_VERSION_6225) += adsp_6225.o
obj-$(CONFIG_MSM_AMSS_VERSION_6320) += adsp_6320.o
obj-$(CONFIG_MSM_AMSS_VERSION_4001) += adsp_4001.o

obj-y += adsp.o adsp_driver.o
obj-y += adsp_video_verify_cmd.o
obj-y += adsp_videoenc_verify_cmd.o
obj-y += adsp_jpeg_verify_cmd.o adsp_jpeg_patch_event.o 
obj-y += adsp_vfe_verify_cmd.o adsp_vfe_patch_event.o 
obj-y += adsp_lpm_verify_cmd.o 
obj-y += audio_out.o audio_in.o audio_mp3.o audio_aac.o audmgr.o audpp.o audplay.o
obj-y += snd.o
obj-y += vocpcm.o
